### ISSUE TITLE
ip黑白名单配置不生效，是我配置错了么？该如何配置？

### ISSUE THREAD

**Issue by heng-git** [apache/incubator-dubbo-admin#182]
service Unique ID   : com.sys.service.DataTimePermissionService (提供得服务)
blacklist:
  - 10.10.50.81
  - 10.10.50.204

**Comment by nzomkxia** [comment]
请发一下具体的配置，预期的结果和实际的结果，我模拟验证下

**Comment by nzomkxia** [comment]
你截图显示的ip和预期拦截的ip不一致，请检查一下是不是写错了？

**Comment by majinkai** [comment]
麻烦问一下，dubbo的版本用的哪个，除了黑名单这两个IP之外，这个服务还有更多的提供者吗

**Comment by heng-git** [comment]
服务提供者只有一台机器， 黑名单这两个是消费者，我的目的是拦截这两个IP请求我的服务

**Comment by heng-git** [comment]
dubbo版本用的是 dubbox2.8.4  ,   是这个版本问题么？

**Comment by majinkai** [comment]
用dubbox2.8.4的那个admin，访问控制生效吗

**Comment by nzomkxia** [comment]
我这里试了一下，用dubbo2.6.4版本，访问控制的黑名单功能可以生效
