### ISSUE TITLE
Dubbo OPS 0.1 无法成功创建规则

### ISSUE THREAD

**Issue by 799983050** [apache/incubator-dubbo-admin#300]
![default](https://user-images.githubusercontent.com/45658355/52761524-9d878f00-304e-11e9-8615-63f5cfd9fd05.png)

点击保存后，提示如下
![default](https://user-images.githubusercontent.com/45658355/52760999-9f505300-304c-11e9-99c6-34e5498b7540.png)
无法看到保存后的数据，刷新查询也没有

**Comment by nzomkxia** [comment]
服务名和应用名二选一，表示这条规则是服务**或者**应用维度的，如果都填了的话 默认会按照应用生效，请按照应用名查询一下是否存在此规则，我会加上一些输入提示，谢谢反馈

**Comment by 799983050** [comment]
![default](https://user-images.githubusercontent.com/45658355/52761381-294ceb80-304e-11e9-9096-f3e99b5ea5c3.png)
按照你说的，按照应用名可以查询处理了，但是后面的操作按钮点击无反应。
PS：有没有服务治理页面功能的使用文档啊

**Comment by nzomkxia** [comment]
文档正在编写中，会放到官网，这个问题我看下

**Comment by nzomkxia** [comment]
@799983050 [路由规则](http://dubbo.apache.org/zh-cn/docs/user/demos/routing-rule.html)
                         [配置规则](http://dubbo.apache.org/zh-cn/docs/user/demos/config-rule.html) 先看下这两个

**Comment by 799983050** [comment]
嗯好的，多谢。

**Comment by nzomkxia** [comment]
> 嗯好的，多谢。

![image](https://user-images.githubusercontent.com/1183397/52768535-c3ba2880-3068-11e9-85a9-4efe380e11ec.png)这里下拉改成 按应用名 另外是否方便留一个联系方式？

**Comment by 799983050** [comment]
QQ可以吧：799983050
