### ISSUE TITLE
provider端使用rmi协议时，报NoSuchMethod错误

### ISSUE THREAD

**Issue by wangjw1989** [apache/incubator-dubbo-admin#325]
System Error, please try again later! Message:Failed to invoke the method getSpanParserPage in the service org.apache.dubbo.rpc.service.GenericService. Tried 3 times of the providers [192.168.163.138:20880] (1/1) from the registry zk:2181 on the consumer 192.168.163.138 using the dubbo version 2.7.0. Last error is: Failed to invoke remote service: interface org.apache.dubbo.rpc.service.GenericService, method: $invoke, cause: Invocation of method [public abstract java.lang.Object org.apache.dubbo.rpc.service.GenericService.$invoke(java.lang.String,java.lang.String[],java.lang.Object[]) throws org.apache.dubbo.rpc.service.GenericException] failed in RMI service [rmi://192.168.163.138:20880/xxxxxxx.SpanParserService]; nested exception is java.lang.NoSuchMethodException: com.sun.proxy.$Proxy98.$invoke(java.lang.String, [Ljava.lang.String;, [Ljava.lang.Object;)

**Comment by nzomkxia** [comment]
泛化调用在处理RMI协议的时候有些问题，正在看，谢谢反馈

**Comment by CrazyHZM** [comment]
看一下这个 issuse #2779 @nzomkxia

**Comment by nzomkxia** [comment]
@CrazyHZM 提个pr到dubbo？修复了Ops这里应该就可以了

**Comment by CrazyHZM** [comment]
@nzomkxia   是的，已经提了pr了，在等待review

**Comment by wangjw1989** [comment]
感谢各位开发者

**Comment by nzomkxia** [comment]
@wangjw1989 这个feature已经合并，会在Dubbo2.7.1发布，到时候使用该版本的Dubbo就可以支持RMI的服务测试了

**Comment by wangjw1989** [comment]
@nzomkxia  收到，多谢
