### ISSUE TITLE
测试页面输测试方法输入参数纯数字符当成整型处理报错java.lang.Integer cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by netsail** [apache/incubator-dubbo-admin#328]
操作步骤：
1、要测试的dubbo服务接口方法：method(String par);
2、在测试页面输测试方法输入参数纯数字符：123
3、结果:失败  报错如下：
message | : | System Error, please try again later! Message:java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String\njava.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String\n\tat org.apache.dubbo.common.bytecode.Wrapper6.invokeMethod(Wrapper6.java)\n\tat org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)\n\tat org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:86)\n\tat org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)\n\tat org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)\n\tat org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:63)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:88)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:79)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:78)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:112)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:39)\n\tat org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73)\n\tat org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:108)\n\tat org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:103)\n\tat org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:200)\n\tat org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)\n\tat org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n
-- | -- | --

**Comment by nzomkxia** [comment]
我看一下，谢谢反馈

**Comment by nzomkxia** [comment]
json在传值的时候，没有区分数字和字符串类型

**Comment by nzomkxia** [comment]
@netsail 试一下develop分支最新的代码

**Comment by netsail** [comment]
@nzomkxia 我那天就在develop分支上测试出这问题。刚查看commit最新时间为2019-02-26 15:57

**Comment by netsail** [comment]
![image](https://user-images.githubusercontent.com/5102157/54099733-b2f59c00-43f5-11e9-8843-1b88004e4db9.png)

@nzomkxia 刚自己测试一遍，发现问题：
虽然前端代码将参数类型改为"parameterTypes":["java.lang.String"]，如截图所示，需要"params":传值应该是这样["1212"]后端才不会invoke报错导致失败。

**Comment by kezhenxu94** [comment]
@netsail 请确保你的代码是最新的, 我本地测试传递的确实是字符串
![image](https://user-images.githubusercontent.com/15965696/54101524-2f40ad00-43ff-11e9-9003-ea31a9cac62a.png)

**Comment by nzomkxia** [comment]
改的是params的类型，@kezhenxu94 嵌套对象是指？我看到你截图里结果是成功的

**Comment by kezhenxu94** [comment]
以上截图中的是对哪些参数是基本数据类型的测试, 比如
![image](https://user-images.githubusercontent.com/15965696/54104946-797c5b00-440c-11e9-83c7-bb189ff4e031.png)
但是像如下这种方法, 则无法有效转换类型了
![image](https://user-images.githubusercontent.com/15965696/54104974-8ef18500-440c-11e9-8600-80e42ea913c3.png)
以上 `User` 是普通的对象, 已经无法正常转换, 还要注意考虑到 `User` 内可能还有对象

**Comment by netsail** [comment]
@kezhenxu94 已更新了最新代码，前端传值没问题，但另一个新问题出现了。执行测试后端报错：
com/esotericsoftware/kryo/io/Output\r\nio.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError:

然后我在dubbo-admin-server项目pom文件加入下面依赖包，解决了
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-serialization-kryo</artifactId>
            <version>${dubbo-version}</version>
        </dependency>

**Comment by kezhenxu94** [comment]
> @kezhenxu94 已更新了最新代码，前端传值没问题，但另一个新问题出现了。执行测试后端报错：
> com/esotericsoftware/kryo/io/Output\r\nio.netty.handler.codec.EncoderException: java.lang.NoClassDefFoundError:
> 
> 然后我在dubbo-admin-server项目pom文件加入下面依赖包，解决了
> 
> ```
>         <dependency>
>             <groupId>org.apache.dubbo</groupId>
>             <artifactId>dubbo-serialization-kryo</artifactId>
>             <version>${dubbo-version}</version>
>         </dependency>
> ```

@netsail 多谢反馈, 但该 bug 还没完全解决

> 操作步骤：
1、要测试的dubbo服务接口方法：method(String par);
2、在测试页面输测试方法输入参数纯数字符：123
3、结果:失败 报错如下：

你测试的方法参数是比较简单的(只包含基本数据类型) `method(String par)`, 如果方法参数包含对象, 还会有这个问题, 需要继续跟进

**Comment by nzomkxia** [comment]
@netsail 你是用了kyro的序列化方式么？

**Comment by kezhenxu94** [comment]
> @netsail 你是用了kyro的序列化方式么？

@nzomkxia 使用 kryo 序列化协议确实能够复现

![image](https://user-images.githubusercontent.com/15965696/54114500-8b1e2c80-4425-11e9-870c-9c20d3be0ea0.png)

**Comment by netsail** [comment]
@nzomkxia 我们provider方使用了kyro的序列化方式
