### ISSUE TITLE
没有使用广播方式，但是出现了多个同端口Provider,而且我关闭项目之后，Provider不会掉

### ISSUE THREAD

**Issue by Xavier125** [apache/incubator-dubbo-admin#329]
![image](https://user-images.githubusercontent.com/45557420/53808407-1b272680-3f8d-11e9-8a93-d178146203ea.png)
我使用的是dubbo-demo-xml-provider的示例项目。配置如下：

```xml
     <!-- provider's application name, used for tracing dependency relationship -->
    <dubbo:application name="demo-provider"/>

    <!-- 使用multicast广播注册中心暴露服务地址 -->
    <dubbo:registry address="zookeeper://wefun.vip:2181" client="curator"/>

    <!--配置这个，注册元数据信息-->
    <dubbo:config-center address="zookeeper://wefun.vip:2181"/>

    <dubbo:metadata-report address="zookeeper://wefun.vip:2181"/>

    <!-- 用dubbo协议在20880端口暴露服务 -->
    <dubbo:protocol name="dubbo" port="20881"/>

```

**Comment by Xavier125** [comment]
过了一天了，今天这个Provider还在
![image](https://user-images.githubusercontent.com/45557420/53847441-b6e77f80-3feb-11e9-8051-aaada6f7ff9e.png)

**Comment by Xavier125** [comment]
麻烦大佬帮忙看一下，谢谢了

**Comment by nzomkxia** [comment]
@Xavier125 看一下zk里面，是不是有对应的数据存在？

**Comment by Xavier125** [comment]
> @Xavier125 看一下zk里面，是不是有对应的数据存在？

这个怎么看啊

**Comment by Xavier125** [comment]
![image](https://user-images.githubusercontent.com/45557420/53855797-28362b00-400a-11e9-8442-29ccc42fbefa.png)
是这样看吗

**Comment by nzomkxia** [comment]
`ls /dubbo/org.apache.dubbo.demo.DemoService/providers`   看一下这里的数据 @Xavier125

**Comment by Xavier125** [comment]
> `ls /dubbo/org.apache.dubbo.demo.DemoService/providers` 看一下这里的数据 @Xavier125

抱歉啊，我真的没有找到你说的这个目录在哪，我现在是在本地跑的前后端不分离的那个springboot的控制台项目，然后zookeeper是在我的linux服务器里面跑着，Provider目前没有运行，你说的这个目录在哪里啊

**Comment by nzomkxia** [comment]
> > `ls /dubbo/org.apache.dubbo.demo.DemoService/providers` 看一下这里的数据 @Xavier125
> 
> 抱歉啊，我真的没有找到你说的这个目录在哪，我现在是在本地跑的前后端不分离的那个springboot的控制台项目，然后zookeeper是在我的linux服务器里面跑着，Provider目前没有运行，你说的这个目录在哪里啊

在zookeeper的服务器节点上，用zkCli进入zookeeper客户端以后，执行 `ls /dubbo/org.apache.dubbo.demo.DemoService/provider`，或者你留个联系方式
