### ISSUE TITLE
不兼容dubbo2.5.7？

### ISSUE THREAD

**Issue by xuyanhua** [apache/incubator-dubbo-admin#340]
你好，我们目前的项目使用的还是dubbo2.5.7，搭建起来最新的dubbo-admin，在服务查询那找不到任务服务。

ps：我主要想用这里面的单元测试功能

**Comment by kexianjun** [comment]
你的意思是服务测试？

**Comment by kezhenxu94** [comment]
> 你好，我们目前的项目使用的还是dubbo2.5.7，搭建起来最新的dubbo-admin，在服务查询那找不到任务服务。
> 
> ps：我主要想用这里面的单元测试功能

@xuyanhua dubbo2.7以下没有元数据, 不支持服务测试哦

**Comment by xuyanhua** [comment]
@kezhenxu94 确定吗？那我是不是只能用泛化调用自己搞了？或者你知道市面上有别的实现了的吗？

**Comment by kezhenxu94** [comment]
是的, 至少目前是不支持得, 可以参看这个 PR #308 , 他也是试图在 2.7 以下进行服务测试

**Comment by xuyanhua** [comment]
好的，谢谢啦~
