### ISSUE TITLE
直线表示这段时间没有请求，没有消费者要请求这个提供者

### ISSUE THREAD

**Issue by Hakon1014** [apache/incubator-dubbo-admin#344]
直线表示这段时间没有请求，没有消费者要请求这个提供者

_Originally posted by @meifu2027 in https://github.com/apache/incubator-dubbo-admin/issues/176#issuecomment-476035887_

额，右边的相应时间图，不是代表有请求吗？右边的有数据了，左边却没请求？

**Comment by meifu2027** [comment]
嗯，你说的有道理，跟我之前遇到过的consumer是0，provider却不是0 的情况比较类似。

**Comment by meifu2027** [comment]
你用的是什么版本的？从这个页面来看这个版本作者的答复是dubbo-monitor不维护了，具体还得他们解答一下

**Comment by nzomkxia** [comment]
dubbo monitor不再维护，后续会通过metrics统计来提供类似信息
