### ISSUE TITLE
zookepeer作为注册时，kill服务服务提供者，管理界面状态不会更新

### ISSUE THREAD

**Issue by eztlvit** [apache/incubator-dubbo-admin#361]
提供者或者消费者kill掉之后，管理界面依然显示那个服务，新增的服务能显示，但服务挂掉之后还一直显示，状态没有更新

**Comment by nzomkxia** [comment]
页面刷新以后，服务列表还是有已经下线的服务么？看下zookeeper里面对应的服务节点是不是还在？

**Comment by lyixi** [comment]
同样的问题
