### ISSUE TITLE
打包出错。。。不知道是node版本还是npm版本问题

### ISSUE THREAD

**Issue by johnxiaohe** [apache/incubator-dubbo-admin#363]
[WARNING] npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[WARNING] npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[WARNING] npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[WARNING] npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

**Comment by nzomkxia** [comment]
这个是warning，不是出错，不会影响构建流程

**Comment by johnxiaohe** [comment]
这个waring出现之后打包就停止了，就一直会停留在这个信息这里 等半小时都没动静 所以很奇怪想问一下这个问题

**Comment by johnxiaohe** [comment]
fetchMetadata: sill pacote range manifest for sort-keys@^1.0.0 fetched in 18954ms
现在nvm install会停留在这里 换了淘宝的和默认的源都是停留在这里 晕了  网上找这个提示 没有sort-key的

**Comment by nzomkxia** [comment]
换一个Npm源也需要这么久么？

**Comment by johnxiaohe** [comment]
不清楚 一直在换 又用代理 最后好在成功了 哈哈
