### ISSUE TITLE
新版本的控制台服务测试里面的方法列表是空的是我理解有问题么不是展示服务端方法的么

### ISSUE THREAD

**Issue by johnxiaohe** [apache/incubator-dubbo-admin#367]
但是服务调用通了，而且服务端和消费端均在admin上有显示
但是点击服务端上面测试的时候就发现方法列表是空的  我写的是最简单的一个sayhello的方法
@GetMapping("/hello/{name}")
    public String sayHello(@PathVariable("name")String name)throws Exception{

        return userInfoISV.sayHello(name);
    }
客户端
@Override
    public String sayHello(String name) {
        return "你好呀，"+name+"先生!";
    }
服务端

以上

**Comment by nzomkxia** [comment]
1. dubbo的版本是不是2.7及2.7以上
2. 有没有在dubbo中配置元数据？

**Comment by johnxiaohe** [comment]
dubbo是2.7 可能是元数据的问题 我还没有看多少文档 谢谢

**Comment by johnxiaohe** [comment]
我发现 我使用远程的注册中心的时候，打包报错是因为test里的一些测试类连不上 里面很多127.0.0.1这些本地连接 哭了

**Comment by johnxiaohe** [comment]
我把测试文件夹全删掉瞬间不报错了 哈哈哈
