### ISSUE TITLE
mvn clean pacckage 报错

### ISSUE THREAD

**Issue by hlongy** [apache/incubator-dubbo-admin#370]
使用 mvn clean package 编译报错
![image](https://user-images.githubusercontent.com/7572189/56482450-da607e00-64f6-11e9-96cc-8c9b6c463340.png)
使用 mvn --projects dubbo-admin-server spring-boot:run 可以运行，但是localhost:8080报的下面的404错误
![image](https://user-images.githubusercontent.com/7572189/56482484-08de5900-64f7-11e9-86b1-d73475c18e83.png)

**Comment by nzomkxia** [comment]
npm的版本需要升级，安装最新的试一下
