### ISSUE TITLE
注册中心配置BUG问题

### ISSUE THREAD

**Issue by johnxiaohe** [apache/incubator-dubbo-admin#372]
http://47.100.58.201/img/git.png 看这张图片 现在单注册中心  我又换了一台电脑测试还是在连玩配置的那台之后会去连一个127.0.0.1:2181 有点晕了  这个另一台的这个项目我上回测试好之后就没动过 难道是zk出现问题了么

**Comment by johnxiaohe** [comment]
# demo-consumer配置文件

#端口配置
server.port=8888

## Dubbo 服务提供者配置
# provider应用名称
spring.application.name=demo-provider
# Dubbo组件扫描的基础包
dubbo.scan.base-packages=com.dubbo.dudemoprovider.serviceImpl
# Dubbo 协议与端口
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880
## Dubbo 注册地址 N/A表示直连方式
dubbo.registry.client=curator  //这个应该是默认的链接方式
dubbo.registry.address=zookeeper://47.100.58.201:2182
dubbo.metadataReport.address=zookeeper://47.100.58.201:2182
spring.main.allow-bean-definition-overriding=true


# 这样应该是单注册中心，但是在连接后 连接到47这个远程zk后 又会提示一次Default schema 好了要加载默认配置了 
### Initiating client connection, connectString=127.0.0.1:2182 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@310b2b6f
### Default schema
### Opening socket connection to server 127.0.0.1/127.0.0.1:2182. Will not attempt to authenticate using SASL (unknown error) 
### Started DudemoProviderApplication in 11.431 seconds (JVM running for 12.39)
### Socket error occurred: 127.0.0.1/127.0.0.1:2182: Connection refused: no further information
### Opening socket connection to server 127.0.0.1/127.0.0.1:2182. Will not attempt to authenticate using SASL (unknown error)
然后就是无限循环

**Comment by johnxiaohe** [comment]
好了  莫民奇妙 什么没动又好了。 唯一动的是修改了元数据注册中心地址位置放到最上面 启动了一下发现没报错 又把它移回原位置了还是没报错。具体原因不知道

**Comment by zhangviv** [comment]
我也遇到这个问题，是因为配置中心里设置注册中心和元数据地址不能填写127.0.0.1，必须填写当前机器的ip地址，这个问题出现在zk3.4.13上，zk3.4.14或者zk3.5.5不会打印那个日志。

**Comment by johnxiaohe** [comment]
这样谢谢啦
