### ISSUE TITLE
服务提供者不消失, 且重复注册

### ISSUE THREAD

**Issue by tracywatthp** [apache/incubator-dubbo-admin#376]
provider-server 停掉后，控制台的服务提供者仍然能够显示，但消费者无法消费，当provider-server重新启动后，控制台服务提供者会再次注册，此时控制台查询服务时会显示2个相同的服务和消费者，每次启动都会从新注册旧的无法清楚。
![image](https://user-images.githubusercontent.com/40331249/56643050-687d6580-66ab-11e9-9ac9-271922692ed8.png)

虽然这样不影响RPC调用， 但是无法从控制台获取服务是否真实存在。。。。

**Comment by nzomkxia** [comment]
@tracywatthp 看一下zookeeper上，对应服务的provider节点

**Comment by carryxyh** [comment]
可能是这个问题导致的：
https://github.com/apache/incubator-dubbo/issues/3785

在旧的版本中由于dynamic的值被错误的设置为false，导致注册的服务都是`持久化`在zk上的。
