### ISSUE TITLE
mvn clean package报错

### ISSUE THREAD

**Issue by zhaojun0193** [apache/incubator-dubbo-admin#378]
报这个错是什么问题呢？
node 的版本是：v9.3.0
npm 的版本是：6.9.0
![image](https://user-images.githubusercontent.com/21002594/56687455-e7ed5200-6708-11e9-81ff-10434f2ff125.png)

**Comment by nzomkxia** [comment]
@zhaojun0193 zhao 已修复，请更新代码再试一下

**Comment by zhaojun0193** [comment]
@nzomkxia  打包成功了，谢谢了！
