### ISSUE TITLE
2.7 以后dubbo-admin 搜索服务提供者不能模糊搜索么？

### ISSUE THREAD

**Issue by hoofungson** [apache/incubator-dubbo-admin#380]
新版的dubbo-admin在搜索服务提供者的时候需要输入全名才能搜出来，老版的dubbo-admin搜索的时候输入服务提供者名称部分字母都能搜出来。还有新版的dubbo-admin怎么配置用户名和密码呢？限制登录后的用户进入dubbo-admin管理服务。

**Comment by nzomkxia** [comment]
@hoofungson 目前版本的支持*查询和自动提示功能，登录功能目前没有

**Comment by shaofei007** [comment]
模糊查询可以支持搜索相关的服务，一次性搜索出来比较方便。
可否把这个作为特性重新打开呢？
我来弄下。
