### ISSUE TITLE
why I cannot visit localhost:8080 ? please help me

### ISSUE THREAD

**Issue by abc598300612** [apache/incubator-dubbo-admin#381]
![image](https://user-images.githubusercontent.com/28611634/56733216-16633f80-6792-11e9-9b8b-b553904b9099.png)

`mvn clean package` success

`mvn --projects dubbo-admin-server spring-boot:run` success

Visit `http://localhost:8080` not success

**Comment by abc598300612** [comment]
![image](https://user-images.githubusercontent.com/28611634/56733541-01d37700-6793-11e9-8969-2a8478067107.png)

Whitelabel Error Page

**Comment by GisDeng** [comment]
Have you solved the problem? I had the same problem
