### ISSUE TITLE
非Spring Boot的provider（SSM项目）想使用元数据中心，该怎么配置applicationContext.xml呢？

### ISSUE THREAD

**Issue by HSomeCao** [apache/incubator-dubbo-admin#384]
我的项目是SSM的。我看了文档说要配置application，但是我只有provider.xml和applicationContext.xml不知道怎么修改。另外创建ZK元数据中心节点的代码是只需要在dubbo-admin里加上吗

**Comment by nzomkxia** [comment]
dubbo admin和dubbo应用的类型无关，只要两边配置的元数据中心和注册中心一致就可以
