### ISSUE TITLE
@Method  设置的retries不生效

### ISSUE THREAD

**Issue by icc99** [apache/incubator-dubbo-admin#387]
在@Reference(methods=@Method(retries=3))不生效

**Comment by kexianjun** [comment]
pls config like 

> @Reference(methods = @Method(name ="sayHello", retries = 3))

and I have test this, works fine for me

**Comment by kexianjun** [comment]
closed first, if you still have problem, pls open an issue in [Dubbo](https://github.com/apache/incubator-dubbo/issues)
