### ISSUE TITLE
mock服务现在具体谁在开发啊

### ISSUE THREAD

**Issue by shaofei007** [apache/incubator-dubbo-admin#390]
如题，就是下面的服务。

![image](https://user-images.githubusercontent.com/26021107/57608723-0fb13680-75a0-11e9-8b7f-de38a00cd3e9.png)

谁正在开发留个联系，联系下啊。

**Comment by nzomkxia** [comment]
你们有这方面的需求么？@shaofei007

**Comment by shaofei007** [comment]
是的。我们本地调试需要一个地方能够模拟服务之外的调用。
这个计划做成什么样子，有具体的方向吗？

**Comment by shaofei007** [comment]
> 你们有这方面的需求么？@shaofei007

 这个你这里目前有什么计划或者方向吗？可否分享下，我这几天弄一弄。

**Comment by nzomkxia** [comment]
@shaofei007 留个联系方式交流下
