### ISSUE TITLE
目前官方最新的dubbo版本为2.7.1，这里面的dubbo版本为2.7.2-SNAPSHOT？

### ISSUE THREAD

**Issue by SunShiFu** [apache/incubator-dubbo-admin#391]
目前官方最新的dubbo版本为2.7.1，这里面的dubbo版本为2.7.2-SNAPSHOT，降级项目代码会报错，项目运行不起来

**Comment by nzomkxia** [comment]
@SunShiFu 里面实现了metrics的采集展示，用到dubbo 2.7.2-SNAPSHOT，该版本已经发布到apache的snapshot仓库
