### ISSUE TITLE
dubbo-admin-ui 启动成功但无法访问

### ISSUE THREAD

**Issue by HuangDayu** [apache/incubator-dubbo-admin#395]
```shell
 I  Your application is running here: http://localhost:8081
```

**Comment by kezhenxu94** [comment]
> Your application is running here: http://localhost:8081

So open your browser and navigate to http://localhost:8081

**Comment by HuangDayu** [comment]
@kezhenxu94 结果是无法访问，修改host为`0.0.0.0`，可以访问，但是出现一下错误：
```shell
Invalid Host header
```
然后在package.json的scripts下的dev添加
```shell
--disableHostCheck=true
```
上面的错误解决，加载了好久，终于可以访问了！！！

**Comment by HuangDayu** [comment]
我的服务是在阿里云 CES上启动的，不是本地。

**Comment by nzomkxia** [comment]
不是本地的话需要设置成真实的机器IP，端口如果没有开放请用nginx做转发

**Comment by chenwei9120** [comment]
一堆bug，页面做的超烂
