### ISSUE TITLE
dabbo-admin-ui编译失败

### ISSUE THREAD

**Issue by NeverGiveUp-Max** [apache/incubator-dubbo-admin#396]
使用的是最新的npm(6.9.0)和node(12.2.0和10.15)都试过，就是编译失败
![QQ截图20190516133020](https://user-images.githubusercontent.com/26043027/57828839-6ce6fb00-77df-11e9-9ddc-ddb6e14f03da.png)
![QQ截图20190516133426](https://user-images.githubusercontent.com/26043027/57828848-73757280-77df-11e9-8622-2698d8467d3c.png)

**Comment by nzomkxia** [comment]
我这里编译出来的项目 不存在last-call-webpack-plugin/src/index.js的文件，是不是版本不一样，清空目录重新编译试试

**Comment by mashengwei567** [comment]
兄弟怎么样，解决了吗？我今天也出现这个问题了
