### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by KyrellLupin** [apache/incubator-dubbo-admin#397]
使用mvn clean package编译时报错，请问该如何解决
[ERROR] /D:/incubator-dubbo-admin-develop/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[22,32] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 程序包 org.apache.dubbo.monitor
[ERROR] /D:/incubator-dubbo-admin-develop/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[26,29] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 类 org.apache.dubbo.admin.service.impl.MetrcisCollectServiceImpl
[ERROR] /D:/incubator-dubbo-admin-develop/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[31,38] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 类 org.apache.dubbo.admin.service.impl.MetrcisCollectServiceImpl
[ERROR] /D:/incubator-dubbo-admin-develop/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[39,9] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 类 org.apache.dubbo.admin.service.impl.MetrcisCollectServiceImpl

**Comment by nzomkxia** [comment]
看下依赖的dubbo 2.7.2-SNAPSHOT有没有下载到

**Comment by KyrellLupin** [comment]
应该是由于网络原因导致dubbo 2.7.2-SNAPSHOT未下载到

**Comment by HarryPotter528** [comment]
我的也是
