### ISSUE TITLE
前端莫名奇妙的崩

### ISSUE THREAD

**Issue by MutualExclusion** [apache/incubator-dubbo-admin#398]
![image](https://user-images.githubusercontent.com/26239970/57910337-a0955400-78b7-11e9-9cd7-52a98e9c6df4.png)
本身对前端一点兴趣都没有。只是这个版本前后端分离。用了以后经常出现前端自己挂掉的问题，还不懂。马上毕设答辩了，这怎么玩！！！

**Comment by nzomkxia** [comment]
提供一下具体的使用场景 npm版本号和复现过程

**Comment by MutualExclusion** [comment]
版本：![image](https://user-images.githubusercontent.com/26239970/57912321-a04b8780-78bc-11e9-8f42-39241b0f3ed3.png)
打包问题：
[INFO] dubbo-admin ........................................ SUCCESS [ 20.901 s]
[INFO] dubbo-admin-ui ..................................... FAILURE [03:21 min]
[INFO] dubbo-admin-server ................................. SKIPPED
[INFO] dubbo-admin-distribution ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:44 min
[INFO] Finished at: 2019-05-17T16:02:44+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run build) on project dubbo-admin-ui: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-admin-ui

**Comment by MutualExclusion** [comment]
此外，系统是linux腾讯云 1G内存 曾经使用nohup 命令启动成功过并运行正常 几天之后访问失败，重启失败

**Comment by MutualExclusion** [comment]
找到问题了 可能是内存不够了 不知道怎么计算运行时的内存

**Comment by nzomkxia** [comment]
maven打包的时候加上 -X 看看具体异常是什么
