### ISSUE TITLE
关于zookeeper配置的问题

### ISSUE THREAD

**Issue by KyrellLupin** [apache/incubator-dubbo-admin#399]
在之前的版本中，根据生产环境启动配置，增加了dubbo-admin-server/src/main/resources/application-production.properties文件，在该文件中配置了dubbo.registry.address,其他文件均未改动，能够成功启动。在今天刚拉下的版本中使用同样的配置启动，报错无法连接到127.0.0.1:2181，即application-production.properties中的地址不生效，但是通过改动dubbo-admin-server/src/main/resources/application.properties中admin.registry.address、admin.config-center、admin.metadata-report.address的默认地址，即可成功启动。是说明未更新，还是我启动方式不对导致的？

**Comment by nzomkxia** [comment]
目前没有`application-production.properties`，只有`application.properties`了，是说明未更新，已修复，谢谢指出
