### ISSUE TITLE
为什么maven会报错，找不到2.7.2的依赖

### ISSUE THREAD

**Issue by myzhulin** [apache/incubator-dubbo-admin#401]
求解，搞了一上午了都没打包成功

**Comment by kexianjun** [comment]
dubbo 2.7.2 还没有发布吧

**Comment by myzhulin** [comment]
clone下来的pom.xml里面是<dubbo-version>2.7.2-SNAPSHOT</dubbo-version>。。。。

**Comment by kexianjun** [comment]
> clone下来的pom.xml里面是2.7.2-SNAPSHOT。。。。

试了下，应该是可以打包的，2.7.2-SNAPSHOT 已经发布到 http://repository.apache.org/content/groups/snapshots/org/apache/dubbo/

**Comment by nzomkxia** [comment]
目前依赖的是2.7.2-SNAPSHOT，相关的仓库已经放到了pom文件里，请检查网络环境
