### ISSUE TITLE
 NoAuth for /dubbo，目录权限问题

### ISSUE THREAD

**Issue by ydaming** [apache/incubator-dubbo-admin#404]
启动后报错了，没有访问dubbo目录的权限：
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /dubbo
使用客户端zkCli.sh连接，addauth digest super:superpw后才可以访问
请问这个要怎么配置

**Comment by ydaming** [comment]
已解决了
在dubbo-admin.xml 里面的dubbo:registry 节点，配置username="super"  password="superpw"就ok了

**Comment by yrjjf** [comment]
碰到了同样的问题， 但是修改  dubbo-admin.xml 里面的dubbo:registry 节点，配置username="super" password="superpw"  仍旧不行， 请问你使用的是什么版本的dubbo-admin

**Comment by yrjjf** [comment]
dubbo-admin.xml 文件的dubbo:registry 节点内容如下：

<dubbo:registry username="test" password="test123" group="${dubbo.registry.group}" address="${dubbo.registry.address}" check="false" file="false" />

**Comment by ydaming** [comment]
> 碰到了同样的问题， 但是修改 dubbo-admin.xml 里面的dubbo:registry 节点，配置username="super" password="superpw" 仍旧不行， 请问你使用的是什么版本的dubbo-admin

我是download zip，下载的master分支
是不是test用户权限不够

**Comment by yrjjf** [comment]
感谢解答！

addauth digest test:test123
setAcl /110 auth: test:test123:cdrwa

[zk: 10.139.32.57:1231(CONNECTED) 1] getAcl /110
'digest,'test:k9K9tr3GCpet5+pKhMkQ+VYqpGs=
: cdrwa


test用户权限应该正常的。 我手工登入zk ，执行 addauth digest test:test123  后，可以正常访问该路径下信息
